#!/bin/bash
set -e

echo "🚀 Setting up local development environment..."
echo ""

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 Checking prerequisites...${NC}"
command -v docker &> /dev/null || { echo "❌ Docker not found"; exit 1; }
command -v terraform &> /dev/null || { echo "❌ Terraform not found"; exit 1; }
command -v pnpm &> /dev/null || { echo "❌ pnpm not found"; exit 1; }
echo -e "${GREEN}✓ All prerequisites found${NC}"
echo ""

echo -e "${BLUE}1️⃣  Starting Ministack + Stackport...${NC}"
docker-compose up -d
sleep 10  # Wait for Ministack healthcheck
echo -e "${GREEN}✓ Ministack running on http://localhost:4566${NC}"
echo -e "${GREEN}✓ Stackport UI running on http://localhost:8080${NC}"
echo ""

echo -e "${BLUE}2️⃣  Installing dependencies...${NC}"
if [ ! -d "node_modules" ]; then
  pnpm install
fi
echo -e "${GREEN}✓ Root dependencies installed${NC}"
echo ""

echo -e "${BLUE}3️⃣  Installing backend/frontend dependencies...${NC}"
cd packages/backend
if [ ! -d "node_modules" ]; then
  pnpm install
fi
cd - > /dev/null
cd packages/frontend
if [ ! -d "node_modules" ]; then
  pnpm install
fi
cd - > /dev/null
echo -e "${GREEN}✓ Dependencies installed${NC}"
echo ""

# Bucket for the Lambda artifact is created here, not by Terraform (see build-artifacts.sh)
echo -e "${BLUE}4️⃣  Building artifacts and uploading Lambda package...${NC}"
./scripts/build-artifacts.sh
echo ""

# Creates the Lambda function from the S3 artifact just uploaded, so it starts with real code, not a placeholder
echo -e "${BLUE}5️⃣  Deploying backend infrastructure (Terraform)...${NC}"
cd infra/environments/local
terraform init -upgrade
terraform apply -auto-approve
cd - > /dev/null
echo -e "${GREEN}✓ Backend infrastructure deployed to Ministack${NC}"
echo ""

echo -e "${BLUE}6️⃣  Configuring frontend with API endpoint...${NC}"
cd infra/environments/local
# Ministack routes API Gateway requests by Host header, not real DNS, so the
# Vite dev-server proxy talks to Ministack directly and spoofs the Host
# header/stage prefix that Ministack expects (see vite.config.ts).
API_GATEWAY_HOST=$(terraform output -raw api_gateway_invoke_host)
API_GATEWAY_STAGE=$(terraform output -raw api_gateway_stage)
MINISTACK_ENDPOINT=$(terraform output -raw aws_endpoint)
cd - > /dev/null

cat > packages/frontend/.env.local << EOF
# Frontend Local Development Configuration
# Auto-generated by setup-local-dev.sh
VITE_BACKEND_ENDPOINT=$MINISTACK_ENDPOINT
VITE_API_GATEWAY_HOST=$API_GATEWAY_HOST
VITE_API_GATEWAY_STAGE=$API_GATEWAY_STAGE
VITE_ENVIRONMENT=local
EOF
echo -e "${GREEN}✓ Frontend configured to proxy /api through Ministack (Host: $API_GATEWAY_HOST, stage: $API_GATEWAY_STAGE)${NC}"
echo ""

echo -e "${BLUE}7️⃣  Creating admin user...${NC}"
PASSWORD=testpass123 ENVIRONMENT=local ./scripts/create-admin-user.sh
echo ""

echo -e "${BLUE}8️⃣  Infrastructure Endpoints:${NC}"

echo -e "${GREEN}✅ Local development environment ready!${NC}"
echo ""
echo -e "${YELLOW}🚀 Next: Start frontend and backend watcher in separate terminals${NC}"
echo ""
echo -e "${YELLOW}Terminal 1 - Backend (auto-rebuild on changes):${NC}"
echo "   ./scripts/watch-backend.sh"
echo ""
echo -e "${YELLOW}Terminal 2 - Frontend:${NC}"
echo "   cd packages/frontend && pnpm dev"
echo ""
echo -e "${YELLOW}Then open: http://localhost:5173${NC}"
echo ""
echo -e "${YELLOW}📝 Login with:${NC}"
echo "   Email:    admin@example.com"
echo "   Password: testpass123"
echo ""
echo -e "${YELLOW}Backend runs as Lambda in Ministack (auto-deploys on file changes)${NC}"
echo ""
echo -e "${YELLOW}🛑 To tear down:${NC}"
echo "   docker-compose down"
echo "   cd infra/environments/local && terraform destroy"
echo ""
